version: '3.9'
services:
  db:
    image: postgres:14
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=groupomania
volumes:
  psql-data:
